# Generated by Django 5.0.1 on 2024-01-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0002_rename_perfomance_performance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="performance",
            name="actor",
        ),
        migrations.RemoveField(
            model_name="performance",
            name="genre",
        ),
        migrations.AddField(
            model_name="play",
            name="actor",
            field=models.ManyToManyField(
                related_name="performance", to="theatre.actor"
            ),
        ),
        migrations.AddField(
            model_name="play",
            name="genre",
            field=models.ManyToManyField(
                related_name="performance", to="theatre.genre"
            ),
        ),
    ]
