# Generated by Django 5.0.1 on 2024-01-24 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0003_remove_performance_actor_remove_performance_genre_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="play",
            old_name="actor",
            new_name="actors",
        ),
        migrations.RenameField(
            model_name="play",
            old_name="genre",
            new_name="genres",
        ),
    ]
