# Generated by Django 5.0.1 on 2024-01-25 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0002_initial"),
        ("theatre", "0004_rename_actor_play_actors_rename_genre_play_genres"),
    ]

    operations = []
